# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdDemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=64)),
                ('ad_type', models.CharField(max_length=64)),
                ('ad_img', models.ImageField(upload_to='upload')),
                ('ad_corner_img', models.ImageField(null=True, upload_to='upload')),
                ('webaccount_type', models.CharField(max_length=64, null=True)),
                ('network', models.CharField(max_length=64, null=True)),
                ('time', models.CharField(max_length=64)),
                ('battery', models.FloatField(null=True)),
            ],
        ),
    ]
