# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 03:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoimage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addemand',
            old_name='ad_corner_img',
            new_name='adCornerImg',
        ),
        migrations.RenameField(
            model_name='addemand',
            old_name='ad_img',
            new_name='adImg',
        ),
        migrations.RenameField(
            model_name='addemand',
            old_name='ad_type',
            new_name='adType',
        ),
        migrations.RenameField(
            model_name='addemand',
            old_name='webaccount_type',
            new_name='wcType',
        ),
    ]
