# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoimage', '0002_auto_20170822_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='addemand',
            name='doc',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='addemand',
            name='title',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
