# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('autoimage', '0003_auto_20170822_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='addemand',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
