# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoimage', '0004_addemand_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='addemand',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
