# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoimage', '0006_addemand_compositeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='addemand',
            name='doc1stLine',
            field=models.IntegerField(null=True),
        ),
    ]
